@startuml packages_autogen_team
set namespaceSeparator none
package "autogen_team" as autogen_team {
}
package "autogen_team.application" as autogen_team.application {
}
package "autogen_team.application.jobs" as autogen_team.application.jobs {
}
package "autogen_team.core" as autogen_team.core {
}
package "autogen_team.data_access" as autogen_team.data_access {
}
package "autogen_team.data_access.adapters" as autogen_team.data_access.adapters {
}
package "autogen_team.evaluation" as autogen_team.evaluation {
}
package "autogen_team.evaluation.metrics" as autogen_team.evaluation.metrics {
}
package "autogen_team.infrastructure" as autogen_team.infrastructure {
}
package "autogen_team.infrastructure.io" as autogen_team.infrastructure.io {
}
package "autogen_team.infrastructure.messaging" as autogen_team.infrastructure.messaging {
}
package "autogen_team.infrastructure.services" as autogen_team.infrastructure.services {
}
package "autogen_team.infrastructure.utils" as autogen_team.infrastructure.utils {
}
package "autogen_team.models" as autogen_team.models {
}
package "autogen_team.registry" as autogen_team.registry {
}
package "autogen_team.registry.adapters" as autogen_team.registry.adapters {
}
package "autogen_team.scripts" as autogen_team.scripts {
}
package "autogen_team.settings" as autogen_team.settings {
}
autogen_team.application.jobs --> autogen_team.core
autogen_team.application.jobs --> autogen_team.data_access
autogen_team.application.jobs --> autogen_team.evaluation
autogen_team.application.jobs --> autogen_team.infrastructure
autogen_team.application.jobs --> autogen_team.models
autogen_team.application.jobs --> autogen_team.registry
autogen_team.data_access.adapters --> autogen_team.data_access
autogen_team.registry.adapters --> autogen_team.registry
autogen_team.registry.adapters --> autogen_team.infrastructure.utils
autogen_team.scripts --> autogen_team.application.jobs
autogen_team.scripts --> autogen_team.infrastructure.io
autogen_team.settings --> autogen_team.application.jobs
@enduml
