---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: opencode-secrets
  namespace: factory
spec:
  encryptedData:
    LITELLM_API_KEY: AgCv+/kR4E0vP1q4UKWv7ydwDEmPyWE8kIW/QYvlNdORSWwVbMPCzDcvs+q/sAEO5NwqIZ4QahOSH2OBfNS050+l0wwkaw9lS2//OxvgS3pJxVysoKSOnUYoymON8XTV49W66VCtqPT+o4kJMwLrO+HHU6LMgOF7YDHY2cQf4dNMwDD3paabCwOIyUWAui/NolTLF+/C9bSlewK+2XFWq/j2zsEKeO/msWftZpOVP8WJE3tWaToe5iuKR+Zr+C/FDwAuHX5vgcPNfinuKHxX9m8En0rvfifJI4xr2iNnryfFBRbLzspekSwUOqYnruTFWGK3eFjV+KMDPEo6HP7/KzQOsp7c7NzM4782QSUbltEGp8EJYonAkiaFRRNVM9qs6QlUcj+EGQXtLpWiUuO0YtVtikS+KQ4viHL1VATAjS/G1/lXCR2iCPivSEhnu91WyJ9l3/72lvb7pjoTREXu5TPgVRqIaG/ZlmChNzGLLZzmpvM5kl+5cvgUYmifu7AVJdzzakdBhaiTNqUpF5PWMEt3MHMqOixih0ObsG1zpRZ4uhN+EZGR9+GihpWMB3OV7vohlN0c6YUyDbNfrgeWBbKumTSO63d5AquWRM2aEwQE94Lz0yPvpfrRnYLyI05Rs49jyIng+/LwikPqj+ggSxZtFw8KC9EttkMmnRlMNubDVFpO6nnJFRyr74tfOq8QRN8QLeMpfL8S
    OPENCODE_API_KEY: AgC7iNH0/Bu1rZWzqS1VnTlJKtOpvvKhPAPuBpcnh7x+nXlpynW43bcI4H375gdu1Oyb57GXCLA9nCVYIPz36qXKofDixZREykrVwivlNcAg2nmz2Z78qeai75HPSDqYmarZTHVitA1wnLY9vrHUMNonzLsfgWkyoyv6DWNa94jDZMsFD6+7cSJXNGJNFJqA/eEw+Jmh96IEJdmfLOF187PcjkPPEK/74Rw6VcI9P6NT027V/Uwrmd9PY9xmBWYknohieBNwLmg/oCFNOVywyXcAwpqQfTTBxxA+ghsLldgBA1ofEpH8iuP5FyhGszKCGxL1enO0cizE0xqURcYUHVlh0mMYKBqBxvdaydYougHzHxEBvZAl5E61v+2GBZUuRx66ElggoZhc1rqu4NkYx9N/RYWDL5P+OvmqloVP+rtjE62uG4SSywXh4fQvpiL9TMwxHH6tvQZOh+IMAzoDUX62hnvJKNe/QDnI2WDHVbiG990P10tv7QaB59hXmCriEp82xnfl3t6Ep06/KeZaHPEZX88EDnon7YLgQtyqi45EJZI5W/IYxrUQxUiV3FqIoRD4ZSjYz5v1+q43Q2Kv75dGlKCoGb31rH5b864jkAbOqByu+SPzycuJG2+/+zqY7GtZzbdHVJ18usqvb6R+5sKZywdfCmOJU5VhlCz3i1XH6Jb4a56/nFRu/gjwzXmEvxpCceFzvyfb
  template:
    metadata:
      name: opencode-secrets
      namespace: factory
