apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: litellm-secrets
  namespace: agents
spec:
  encryptedData:
    LITELLM_MASTER_KEY: AgCwuVB6kpDBY//lHKGJX50doROEYLB6qRvHeUDavjkWz31B1RzE48+cTwutUJR6dU4Q5NWVopZsi9KxzC7mfH90R4xoLR9kj1D/JLVFjDpInDX+F6iLqS6tyNJenO9YOCiJ+jfxrHXPVN1k0slsqGuv0vilC0F4Z8Gmd7dbrlDW6f1R36FfAki+PQVmqaTBeBeA5xxIU08d0q+szOAJzcKNvtiGQBCE1ZuaJLS/uDAoF23DCaa2bwsgHcbpHcJhis/nGOkNImC391WGs3uRXNMcpSzEEPdkkLqQPH44VpyzzAlFlk5axADv8y1o5g86RdStUmDYvnmO8COBiShs0nrgB0sFjQmpN59XEzbIDjnjIUgzn4YeBRvdPDyG+43Yd+TBXAeYMhMK8se+MdF8DVWS0XaektNX7y1jSu/C6lfLrd9HS+cYtKEEURndQ5wjRh7myKWIFU8swuQIWO+3Hp68u/wFP5NAJLnO96Yl4Tm5huBuaZEjJe7LcIgCzoUBO5bWWTbwC2vp6Qh56eOd1T1c2r8+w/3lVJhQfLw/cwQSyn+cBxJ5b9VMCSqmL9Mbefpwu2rmrBjlK+X4r4RtPS/6jb9sXnojjmQMHU1odCWEDXGr4kuzWaVm9+yG6taEDYTUruZQfyvJmQcNpREZs28kCyeYCih5YgNaz2kXfc8gLMo3YzT9QI1uj1DWBVe6P2sxiYorb7X4
  template:
    metadata:
      name: litellm-secrets
      namespace: agents
