name: Check
permissions:
  contents: read
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  rust-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt, clippy
          
      - name: Install Protoc
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler
          
      - name: Check Formatting
        run: cargo fmt --all -- --check
        
      - name: Lint with Clippy
        run: cargo clippy --workspace -- -D warnings
        
      - name: Run Workspace Tests
        run: cargo test --workspace -- --skip smoke
